name: Go_Bot

on:
  schedule:
  - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download dependencies
        run: go mod download
      - name: Run go project
        run: go run main.go

        env:
          MY_GITHUB_EMAIL: ${{ secrets.MY_GITHUB_EMAIL }}
          MY_GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
          MY_GITHUB_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}

      - name: update the list
        run: |
          git config user.name "${{ secrets.MY_GITHUB_USERNAME }}"
          git config user.email " ${{ secrets.MY_GITHUB_EMAIL }}"
          git checkout master
          git add .
          git commit -m "framework list updated"
          git push -u origin master
