name: Go_Bot

on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run go executable file
        run: ./main
        env:
          MY_GITHUB_EMAIL: ${{ secrets.MY_GITHUB_EMAIL }}
          MY_GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
          MY_GITHUB_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}

      - name: update the list
        run: |
          git config user.name "${{ secrets.MY_GITHUB_USERNAME }}"
          git config user.email " ${{ secrets.MY_GITHUB_EMAIL }}"
          git checkout master
          git add .
          git commit -m "chore: framework list updated"
          git push -u origin master
