name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 1.23

      - name: Download dependencies
        run: go mod download
      - name: Build go executable
        run: go build main.go
      - name: Run go project
        run: ./main

        env:
          MY_GITHUB_EMAIL: ${{ secrets.MY_GITHUB_EMAIL }}
          MY_GITHUB_USERNAME: ${{ secrets.MY_GITHUB_USERNAME }}
          MY_GITHUB_ACCESS_TOKEN: ${{ secrets.MY_GITHUB_ACCESS_TOKEN }}

      - name: update the list
        run: |
          git config user.name "${{ secrets.MY_GITHUB_USERNAME }}"
          git config user.email " ${{ secrets.MY_GITHUB_EMAIL }}"
          git checkout master
          git add .
          git commit -m "chore: executable file created & framework list updated"
          git push -u origin master
