name: Go

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Download dependencies
        run: go mod download

      - name: update the list
        run: |
          git config user.name "${MY_GITHUB_USERNAME}"
          git config user.email "${MY_GITHUB_EMAIL}"
          git checkout master
          git commit -m "project list updated"
          git push -u origin master
